Portfolio/hr/country/urls.py
from django.urls import path
from . import views

app_name = 'country'
urlpatterns = [
    path('', views.CountryMain.as_view(), name='index'),
    path('create/', views.CountryCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.CountryUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.CountryDelete.as_view(), name='delete'),
]

Portfolio/hr/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'
urlpatterns = [
    path('', views.EmployeeMain.as_view(), name='index'),
    path('create/', views.EmployeeCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.EmployeeUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.EmployeeDelete.as_view(), name='delete'),
]

Portfolio/hr/hr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # App
    path('', include('home.urls')),
    path('department/', include('department.urls')),
    path('job/', include('job.urls')),
    path('employee/', include('employee.urls')),
    path('country/', include('country.urls')),
]

Portfolio/hr/country/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Country(models.Model):
    name = models.CharField(
        max_length=150,
        help_text='Enter a Country name',
        validators=[MinLengthValidator(2, "The name must be more than 1 character")],
    )
    code = models.CharField(
        max_length=25,
        help_text='Enter a Code',
        validators=[MinLengthValidator(2, "The name must be more than 1 character")],
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

Portfolio/hr/country/forms.py
from django.forms import ModelForm
from .models import Country

# Create the form class.
class CountryForm(ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

Portfolio/hr/country/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Country
from .forms import CountryForm

class CountryMain(LoginRequiredMixin, View) :
    def get(self, request):
        count = Country.objects.all().count()
        list_objects = Country.objects.order_by('name')

        ctx = {'country_count': count, 'country_list': list_objects, 'title': 'Countries'}
        return render(request, 'country/country_list.html', ctx)

class CountryCreate(LoginRequiredMixin, CreateView):
    model = Country
    fields = '__all__'
    success_url = reverse_lazy('country:index')


class CountryUpdate(LoginRequiredMixin, UpdateView):
    model = Country
    fields = '__all__'
    success_url = reverse_lazy('country:index')


class CountryDelete(LoginRequiredMixin, DeleteView):
    model = Country
    fields = '__all__'
    success_url = reverse_lazy('country:index')

Portfolio/hr/country/templates/country/country_confirm_delete.html
{% extends 'bootstrap/checkout.html' %}
{% load static %}

{% block body_title %}
    <h2 class="mb-3" style="text-align:center;">Delete Country</h2>
{% endblock %}

{% block form %}
    <p style="text-align:center;">Are you sure you want to delete the country:
        <strong>{{ country }}</strong>
    </p>

    <form action="" method="POST" style="text-align:center;">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'country:index' %}' ;
            return false;" value="Cancel">
    </form>

{% endblock %}

Portfolio/hr/country/templates/country/country_form.html
{% extends 'bootstrap/checkout.html' %}
{% load static %}

{% block body_title %}
    <h4 class="mb-3">Country</h4>
{% endblock %}

{% block form %}
    <form action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            {% if field.html_name == "name" %}
                <div class="mb-3">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    <input type="text" class="form-control" id="{{ field.html_name }}" name="{{ field.html_name }}"
                           {% if field.value %} value="{{ field.value }}" {% endif %} >
                </div>
            {% endif %}
        {% endfor %}

        <div class="row">
        {% for field in form %}
            {% if field.html_name != "name" %}
                <div class="mb-3 col-md-6">
                    {{ field.label_tag }}
                    {% if field.errors %}<div style="color:red;">{{ field.errors }}</div>{% endif%}
<!--                    <input type="text" class="form-control" id="{{ field.html_name }}" name="{{ field.html_name }}"-->
<!--                           {% if field.value %} value="{{ field.value }}" {% endif %} >-->
                    <div>{{ field }}</div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
            <input class="col-md-2" type="submit" onclick="window.location='{% url 'employee:index' %}' ;
              return false;" value="Cancel">
            <input class="col-md-2" type="submit" value="Save">
    </form>
{% endblock %}

Portfolio/hr/country/templates/country/country_list.html
{% extends 'bootstrap/dashboard.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    {% if country_list %}
                <h2>Countries</h2>
                <a href="{% url 'country:create' %}">
                    <button type="button" class="btn btn-primary">Create</button>
                </a>
                <div class="table-responsive" style="margin-top: 5px;">
                    <table class="table table-striped table-sm">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Code</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for country in country_list %}
                        <tr>
                            <td>
                                <a href="{% url 'country:update' country.id %}">
                                    {{ country.name }}
                                </a>
                            </td>
                            <td>{{ country.code }}</td>
                            <td>
                                <a href="{% url 'country:delete' country.id %}">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill"
                                         fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
        d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1
        0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8
        5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                    </svg>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

    {% endif %}
{% endblock %}