Portfolio/hr/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'
urlpatterns = [
    path('', views.EmployeeMain.as_view(), name='index'),
    path('create/', views.EmployeeCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.EmployeeUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.EmployeeDelete.as_view(), name='delete'),
]

Portfolio/hr/hr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # App
    path('', include('home.urls')),
    path('department/', include('department.urls')),
    path('job/', include('job.urls')),
    path('employee/', include('employee.urls')),
    path('country/', include('country.urls')),
]

Portfolio/hr/job/urls.py
from django.urls import path
from . import views

app_name = 'job'
urlpatterns = [
    path('', views.JobMain.as_view(), name='index'),
    path('create/', views.JobCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.JobUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.JobDelete.as_view(), name='delete'),
]

Portfolio/hr/job/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from department.models import Department

class Job(models.Model):
    name = models.CharField(
        max_length=150,
        help_text='Enter a Job position name',
        validators=[MinLengthValidator(2, "The name must be more than 1 character")],
        verbose_name='job position',
    )
    number_employees = models.IntegerField(
        blank=True,
        help_text='Enter a Number of Employees',
        verbose_name='Number of employees',
    )
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(
        blank=True,
        help_text='Enter a Description',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

Portfolio/hr/job/forms.py
from django.forms import ModelForm
from .models import Job

# Create the form class.
class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = '__all__'

Portfolio/hr/job/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Job
from .forms import JobForm

class JobMain(LoginRequiredMixin, View) :
    def get(self, request):
        count = Job.objects.all().count()
        list_objects = Job.objects.order_by('name')

        ctx = {'job_count': count, 'job_list': list_objects, 'title': 'Job Positions'}
        return render(request, 'job/job_list.html', ctx)


class JobCreate(LoginRequiredMixin, CreateView):
    model = Job
    fields = '__all__'
    success_url = reverse_lazy('job:index')


class JobUpdate(LoginRequiredMixin, UpdateView):
    model = Job
    fields = '__all__'
    success_url = reverse_lazy('job:index')


class JobDelete(LoginRequiredMixin, DeleteView):
    model = Job
    fields = '__all__'
    success_url = reverse_lazy('job:index')

Portfolio/hr/job/templates/job/job_confirm_delete.html
{% extends 'bootstrap/checkout.html' %}
{% load static %}

{% block body_title %}
    <h2 class="mb-3" style="text-align:center;">Delete Job Position</h2>
{% endblock %}

{% block form %}
    <p style="text-align:center;">Are you sure you want to delete the job:
        <strong>{{ job }}</strong>
    </p>

    <form action="" method="POST" style="text-align:center;">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'job:index' %}' ;
        return false;" value="Cancel">
    </form>

{% endblock %}

Portfolio/hr/job/templates/job/job_form.html
{% extends 'bootstrap/checkout.html' %}
{% load static %}

{% block body_title %}
    <h4 class="mb-3">Job Position</h4>
{% endblock %}

{% block form %}
    <form action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            {% if field.html_name == "name" %}
                <div class="mb-3">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    <input type="text" class="form-control" id="{{ field.html_name }}" name="{{ field.html_name }}"
                           {% if field.value %} value="{{ field.value }}" {% endif %} >
                </div>
            {% endif %}
        {% endfor %}

        <div class="row">
        {% for field in form %}
            {% if field.html_name != "name" %}
                <div class="mb-3 col-md-6">
                    {{ field.label_tag }}
                    {% if field.errors %}<div style="color:red;">{{ field.errors }}</div>{% endif%}
<!--                    <input type="text" class="form-control" id="{{ field.html_name }}" name="{{ field.html_name }}"-->
<!--                           {% if field.value %} value="{{ field.value }}" {% endif %} >-->
                    <div>{{ field }}</div>
                </div>
            {% endif %}
        {% endfor %}
        </div>
            <input class="col-md-2" type="submit" onclick="window.location='{% url 'employee:index' %}' ;
              return false;" value="Cancel">
            <input class="col-md-2" type="submit" value="Save">
    </form>
{% endblock %}

Portfolio/hr/job/templates/job/job_list.html
{% extends 'bootstrap/dashboard.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    {% if job_list %}
                <h2>Job Positions</h2>
                <a href="{% url 'job:create' %}">
                    <button type="button" class="btn btn-primary">Create</button>
                </a>
                <div class="table-responsive" style="margin-top: 5px;">
                    <table class="table table-striped table-sm">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Departament</th>
                            <th>Number Employees</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for job in job_list %}
                        <tr>
                            <td>
                                <a href="{% url 'job:update' job.id %}">
                                    {{ job.name }}
                                </a>
                            </td>
                            <td>{{ job.department }}</td>
                            <td>{{ job.number_employees }}</td>
                            <td>
                                <a href="{% url 'job:delete' job.id %}">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill"
                                         fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
        d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1
        0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8
        5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                    </svg>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
    {% endif %}
{% endblock %}